# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.13.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
print(np.zeros(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [13]:
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
z = np.zeros(10)
z[4] = 1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [22]:
z = np.arange(10, 50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
z = np.arange(9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [25]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [31]:
z = np.eye(3, 3)
print(z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
z = np.random.random((3, 3, 3))
print(z)

[[[ 0.54308501  0.38277453  0.64441375]
  [ 0.16357292  0.49775442  0.39624371]
  [ 0.44473463  0.5591938   0.03093905]]

 [[ 0.50181885  0.51171345  0.12612597]
  [ 0.58219531  0.44128213  0.06782652]
  [ 0.98387609  0.71152323  0.35522516]]

 [[ 0.67213522  0.59232995  0.38997787]
  [ 0.45239096  0.28229258  0.48800295]
  [ 0.18597379  0.57500719  0.98596487]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
z = np.random.random((10, 10))
ma = z.max()
mi = z.min()
print(z)
print(ma, mi)

[[ 0.72073884  0.5639478   0.22894531  0.18995118  0.29054222  0.43435713
   0.30669082  0.11343338  0.23739755  0.07886164]
 [ 0.28505265  0.97279479  0.35168074  0.99661888  0.1652565   0.21238001
   0.40977219  0.1685802   0.41214648  0.06466403]
 [ 0.59979553  0.44807911  0.85537593  0.75024354  0.16063606  0.69712421
   0.39523329  0.4025719   0.52251056  0.77497729]
 [ 0.4905683   0.69834955  0.88895843  0.57275731  0.64138961  0.19269417
   0.82131746  0.73287793  0.95390931  0.32419953]
 [ 0.49762148  0.97116903  0.30805695  0.13411835  0.98166322  0.01204516
   0.52371894  0.07251135  0.3135053   0.782835  ]
 [ 0.30404307  0.14869151  0.43270791  0.348487    0.97322438  0.8269144
   0.19535604  0.39411348  0.14859988  0.41659681]
 [ 0.67162344  0.16225716  0.65905921  0.04356852  0.37876326  0.42621849
   0.85570437  0.80480545  0.21931461  0.00310441]
 [ 0.7448589   0.19626784  0.98050796  0.30166661  0.19181538  0.73996416
   0.21929294  0.64207324  0.84969178  0.21630334]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
z = np.random.random(30)
m = z.mean()
print(m)

0.429910787852


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [58]:
z = np.ones((5, 5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [71]:
z = np.ones((1, 1))
z = np.pad(z, pad_width=1, mode='constant', constant_values=2)
z = np.pad(z, pad_width=1, mode='constant', constant_values=3)
z = np.pad(z, pad_width=1, mode='constant', constant_values=4)
z = np.pad(z, pad_width=1, mode='constant', constant_values=5)
print(z)

[[ 5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  4.  4.  4.  4.  4.  4.  4.  5.]
 [ 5.  4.  3.  3.  3.  3.  3.  4.  5.]
 [ 5.  4.  3.  2.  2.  2.  3.  4.  5.]
 [ 5.  4.  3.  2.  1.  2.  3.  4.  5.]
 [ 5.  4.  3.  2.  2.  2.  3.  4.  5.]
 [ 5.  4.  3.  3.  3.  3.  3.  4.  5.]
 [ 5.  4.  4.  4.  4.  4.  4.  4.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [74]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
z = np.diag(1 + np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [90]:
z = np.diag( 1 + np.arange(7), k=0)
print(z)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [99]:
z = np.zeros((8, 8))#как шахматная доска
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [100]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [106]:
z = np.array([[1, 0], [0, 1]])
z = np.tile(z, (4, 4))
print(z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [110]:
z = np.random.random((5, 5))
print(z)

[[ 0.8282619   0.74258889  0.39362057  0.37914075  0.61089414]
 [ 0.20346009  0.29602577  0.39586902  0.43433487  0.48704848]
 [ 0.24875584  0.7045876   0.47080487  0.38864784  0.66463976]
 [ 0.40823757  0.49835116  0.96366954  0.4303922   0.61335639]
 [ 0.7687332   0.07124272  0.22339913  0.83589781  0.58501534]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [111]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [113]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
z = np.dot(a, b)
print(z)

[[ 0.35666782  0.41136673]
 [ 0.99235455  1.00703526]
 [ 1.22826754  1.48460809]
 [ 0.38174216  0.47312423]
 [ 0.40083553  0.29245393]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [116]:
z = np.arange(11)
z[3:9] = -z[3:9]
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [140]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [149]:
print(Z**Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
[[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [153]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [172]:
z = np.random.uniform(-10, +10, 10)
print(z)
print(np.ceil(z))
print(np.copysign(np.ceil(np.abs(z)), z))

[ 7.6559497   5.66385971  5.70254357  1.48082042  0.06782627  0.76714613
  8.77829068  5.70968274 -3.69629589  6.56937624]
[ 8.  6.  6.  2.  1.  1.  9.  6. -3.  7.]
[ 8.  6.  6.  2.  1.  1.  9.  6. -4.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [189]:
a = np.random.randint(0, 10, 10)#рандом целых чисел
b = np.random.randint(0, 10 ,10)
print(a)
print(b)
print(np.intersect1d(a, b))#пересечение множеств

[7 4 4 4 5 9 1 5 3 4]
[6 0 2 8 3 8 0 9 9 8]
[3 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [196]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [213]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2018-05-17 2018-05-18 2018-05-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
z = np.arange('2018-06', '2018-07', dtype='datetime64[D]')
print(z)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [11]:
a = np.ones(3)
b = np.ones(3) * 2
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
print(a)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [15]:
z = np.random.uniform(0,10,10)
print(z)
print(z - z % 1)
print(np.floor(z))
print(np.ceil(z) - 1)
print(z.astype(int))
print(np.trunc(z))

[ 2.51606043  3.47688793  3.52691013  0.75128346  1.97279833  1.82446201
  4.49588623  2.88409152  7.59966482  3.33598551]
[ 2.  3.  3.  0.  1.  1.  4.  2.  7.  3.]
[ 2.  3.  3.  0.  1.  1.  4.  2.  7.  3.]
[ 2.  3.  3.  0.  1.  1.  4.  2.  7.  3.]
[2 3 3 0 1 1 4 2 7 3]
[ 2.  3.  3.  0.  1.  1.  4.  2.  7.  3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
z = np.zeros((5, 5))
z += np.arange(5)
print(z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [21]:
def gen():
    for x in range(10):
        yield x
z = np.fromiter(gen(), dtype=float, count=-1)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [22]:
z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [23]:
z = np.random.random(10)
z.sort()
print(z)

[ 0.04333149  0.1731339   0.32276804  0.35879975  0.58035179  0.61333758
  0.66092302  0.79389825  0.84589836  0.99253736]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [24]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [25]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
c = np.allclose(a, b)
print(c)
c = np.array_equal(a, b)
print(c)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [28]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [29]:
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)
print(r)
print(t)

[ 0.71037902  1.0389343   0.97936123  1.22141573  0.48663814  0.31197969
  0.3743067   0.22496697  0.72196389  0.66982441]
[ 1.12018194  0.42414601  0.11126248  0.65961819  1.47791711  0.61870353
  1.26888465  0.18992128  0.7931373   0.56904139]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [30]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[ 0.5263161   0.          0.28071207  0.42577816  0.86569392  0.51849915
  0.49213506  0.70658241  0.20314033  0.59903359]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [33]:
z = np.zeros((5, 5), [('x', float),('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [35]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.16363712


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [36]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


#### 49. How to print all the values of an array? (★★☆)

In [37]:
np.set_printoptions(threshold=np.nan)
z = np.zeros((16, 16))
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [41]:
z = np.arange(100)
v = np.random.uniform(0,100)
ind = (np.abs(z-v)).argmin()
print(z[ind])

56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [42]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [43]:
z = np.random.random((10, 2))
x, y = np.atleast_2d(z[:,0], z[:,1])
d = np.sqrt( (x - x.T) ** 2 + (y - y.T) ** 2)
print(d)
import scipy
import scipy.spatial
z = np.random.random((10, 2))
d = scipy.spatial.distance.cdist(z, z)
print(d)

[[ 0.          0.4069219   0.1293898   0.72107744  0.59657716  0.31148963
   0.77799725  0.95196101  0.28358439  0.2728573 ]
 [ 0.4069219   0.          0.42929991  0.62342131  0.29109318  0.52667903
   0.37346898  0.56616647  0.45864035  0.30719558]
 [ 0.1293898   0.42929991  0.          0.61443457  0.66533289  0.18227338
   0.80054482  0.9312727   0.15774003  0.38124248]
 [ 0.72107744  0.62342131  0.61443457  0.          0.89915827  0.49335207
   0.79484524  0.68071576  0.46890078  0.84853756]
 [ 0.59657716  0.29109318  0.66533289  0.89915827  0.          0.79654516
   0.31320835  0.6265408   0.73165803  0.36181837]
 [ 0.31148963  0.52667903  0.18227338  0.49335207  0.79654516  0.
   0.87564866  0.94453268  0.06919335  0.55322797]
 [ 0.77799725  0.37346898  0.80054482  0.79484524  0.31320835  0.87564866
   0.          0.32607423  0.80648     0.61480527]
 [ 0.95196101  0.56616647  0.9312727   0.68071576  0.6265408   0.94453268
   0.32607423  0.          0.88059189  0.86372802]
 [ 0.283

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [44]:
z = np.arange(10, dtype=np.float32)
z = z.astype(np.int32, copy=False)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [45]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

TypeError: must be str or None, not bytes

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [46]:
z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [48]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
print(g)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [49]:
n = 10
p = 3
z = np.zeros((n, n))
np.put(z, np.random.choice(range(n * n), p, replace=False), 1)
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [50]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)
print(y)

[[  4.29821991e-01   3.71726951e-01  -3.39067010e-01  -2.83449832e-01
    3.34878300e-01   4.31335839e-01  -2.64510251e-01  -5.22677108e-01
    1.00399510e-01  -2.58458390e-01]
 [ -1.39837724e-01  -2.29020588e-01   4.42885109e-01  -1.28374227e-01
    1.95192500e-01   8.57805045e-03   8.67912850e-02  -1.01086320e-02
   -1.70724702e-01  -5.53810709e-02]
 [  5.74459468e-02  -1.91304634e-01   4.65698159e-02  -5.31080719e-02
    2.42209470e-01  -3.75800593e-01   1.26097353e-01  -5.04298894e-02
    1.98618916e-01  -2.98312805e-04]
 [ -1.85020764e-01  -3.45465087e-01  -1.84409003e-01   4.38620861e-02
   -4.14478008e-01   2.68548516e-01   4.87875397e-01  -1.03564587e-01
   -9.78254648e-02   5.30476915e-01]
 [ -2.84617604e-01   4.57647690e-01   4.65955117e-01  -3.18133562e-01
    3.57862228e-01  -2.50923476e-01   1.35133591e-01  -3.13427426e-01
   -1.74116558e-01  -7.53800003e-02]]


#### 59. How to sort an array by the nth column? (★★☆)

In [51]:
z = np.random.randint(0, 10, (3, 3))
print(z)
print(z[z[:,1].argsort()])

[[5 0 1]
 [1 2 2]
 [8 1 7]]
[[5 0 1]
 [8 1 7]
 [1 2 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [52]:
z = np.random.randint(0, 3, (3, 10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [53]:
z = np.random.uniform(0, 1, 10)
k = 0.5
m = z.flat[np.abs(z - k).argmin()]
print(m)

0.538271603947


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [54]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3).reshape(1, 3)
it = np.nditer([a, b, None])
for x, y, z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [55]:
class Narr(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

z = Narr(np.arange(10), "range_10")
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [56]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
z += np.bincount(i, minlength=len(z))
print(z)
np.add.at(z, i, 1)
print(z)

[ 3.  4.  2.  1.  6.  2.  1.  4.  2.  5.]
[  5.   7.   3.   1.  11.   3.   1.   7.   3.   9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [57]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i, x)
print(f)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [59]:
w, h = 16, 16
i = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
f = i[...,0] * (256 * 256) + i[...,1] * 256 + i[...,2]
n = len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [60]:
a = np.random.randint(0, 10, (3, 4, 3, 4))
sum = a.sum(axis=(-2, -1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[65 49 62 58]
 [45 75 45 56]
 [65 45 59 71]]
[[65 49 62 58]
 [45 75 45 56]
 [65 45 59 71]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [63]:
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s, weights=d)
d_counts = np.bincount(s)
d_means = d_sums / d_counts
print(d_means)
import pandas as pd
print(pd.Series(d).groupby(s).mean())

[ 0.42816207  0.50801292  0.37146373  0.3907794   0.58264473  0.33676938
  0.43180775  0.42358585  0.48518902  0.48148626]
0    0.428162
1    0.508013
2    0.371464
3    0.390779
4    0.582645
5    0.336769
6    0.431808
7    0.423586
8    0.485189
9    0.481486
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [64]:
a = np.random.uniform(0, 1, (5, 5))
b = np.random.uniform(0, 1, (5, 5))

# Slow version  
np.diag(np.dot(a, b))

# Fast version
np.sum(a * b.T, axis=1)

# Faster version
np.einsum("ij,ji->i", a, b)

array([ 0.71006384,  2.32997387,  1.66339267,  1.16929895,  1.01714142])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [65]:
z = np.array([1, 2, 3, 4, 5])
nz = 3
z0 = np.zeros(len(z) + (len(z) - 1) * (nz))
z0[::nz + 1] = z
print(z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [66]:
a = np.ones((5, 5, 3))
b = 2 * np.ones((5, 5))
print(a * b[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [67]:
a = np.arange(25).reshape(5, 5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [68]:
faces = np.random.randint(0, 100, (10, 3))
f = np.roll(faces.repeat(2, axis=1), -1, axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f, axis=1)
g = f.view(dtype=[('p0', f.dtype),('p1', f.dtype)] )
g = np.unique(g)
print(g)

[( 6, 70) ( 6, 85) ( 9, 10) ( 9, 15) (10, 15) (12, 20) (12, 66) (17, 41)
 (17, 68) (19, 28) (19, 90) (20, 40) (20, 66) (20, 86) (28, 90) (31, 51)
 (31, 96) (40, 86) (41, 68) (47, 71) (47, 75) (51, 96) (58, 81) (58, 92)
 (70, 85) (71, 75) (71, 88) (71, 98) (81, 92) (88, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [69]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [70]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
z = np.arange(20)
print(moving_average(z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [71]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z = rolling(np.arange(10), 3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [72]:
z = np.random.randint(0,2,100)
np.logical_not(z, out=z)

z = np.random.uniform(-1.0, 1.0, 100)
np.negative(z, out=z)

array([-0.14662673,  0.07666813,  0.89655291, -0.64992018,  0.98973751,
        0.71998684, -0.97393585,  0.95896161,  0.33695185, -0.53338443,
        0.70196207, -0.38394669, -0.01767426,  0.61189025, -0.77664677,
       -0.73033816,  0.81506148,  0.22291183, -0.30246494, -0.71886219,
       -0.51495771,  0.55615601,  0.40405204,  0.46244159, -0.29100994,
        0.37623752,  0.2978564 ,  0.17047726, -0.89406521,  0.78866067,
       -0.8967314 ,  0.38789103, -0.07927997, -0.07594232, -0.68618826,
       -0.20835326, -0.70217481,  0.87666219, -0.70132753, -0.25110947,
       -0.84368693,  0.62347389,  0.47106861, -0.85327365,  0.19504231,
        0.27065016, -0.16070461, -0.14257464,  0.81024039,  0.73323712,
        0.11485543, -0.58671546,  0.94145751, -0.86878178,  0.29130352,
        0.65274297,  0.21029416, -0.49344452, -0.64940421, -0.57137918,
       -0.11958578, -0.8105155 ,  0.43188518,  0.60198585, -0.44033785,
        0.16290129,  0.58579972,  0.46461718, -0.61150225, -0.12

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [73]:
def distance(p0, p1, p):
    t = p1 - p0
    l = (t ** 2).sum(axis=1)
    u = -((p0[:,0] - p[...,0]) * t[:,0] + (p0[:,1] - p[...,1]) * t[:,1]) / l
    u = u.reshape(len(u),1)
    d = p0 + u * t - p
    return np.sqrt((d ** 2).sum(axis=1))

p0 = np.random.uniform(-10, 10, (10, 2))
p1 = np.random.uniform(-10, 10, (10, 2))
p  = np.random.uniform(-10, 10, (1, 2))
print(distance(p0, p1, p))

[  2.1533401    0.31262975   0.83579666   0.02196539   9.83307279
   1.16183383   1.53450071   3.56430542  10.4338755    6.33533289]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [74]:
p0 = np.random.uniform(-10, 10, (10, 2))
p1 = np.random.uniform(-10,10,(10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(p0, p1, p_i) for p_i in p]))

[[  8.88964761   2.70645446   6.07971512   7.18013454   8.16746113
    2.03546635   0.94931746   4.05898421   5.72080476   7.72962764]
 [  7.20653975  10.61292591   4.5516303   11.92485131   9.48017137
   17.5262574   13.86639649  10.77341663   9.63022523   9.11727296]
 [  4.02155412   7.02914064   1.0241196    9.76571578   6.67549557
   16.56824906  10.46567731   7.37511114   5.7952187    9.85180337]
 [  0.27961427   3.86130784   1.09087217   5.44642755   2.62465652
   12.24006426   6.98607841   3.8920635    4.65577705   6.24177077]
 [  2.30874819   5.13469833   0.74029885   8.54846086   5.1434168
   15.95221907   8.65309543   5.56362941   3.83883371  10.10598071]
 [  5.96354753   9.68898706   5.09218336  10.27064359   8.04154275
   15.69428763  12.77404215   9.67914308   9.66609769   7.36747951]
 [  0.51665881   4.69359009   7.18919276   1.95185739   0.67081442
    6.69192797   6.99084534   3.88701686   9.2766933    0.98892819]
 [ 13.59386881   8.30539537   0.36507227   9.84653901  1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [76]:
z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill  = 0
position = (1, 1)

r = np.ones(shape, dtype=z.dtype) * fill
p  = np.array(list(position)).astype(int)
rs = np.array(list(r.shape)).astype(int)
zs = np.array(list(z.shape)).astype(int)

r_start = np.zeros((len(shape),)).astype(int)
r_stop  = np.array(list(shape)).astype(int)
z_start = (p - rs // 2)
z_stop  = (p + rs // 2) + rs % 2

r_start = (r_start - np.minimum(z_start,0)).tolist()
z_start = (np.maximum(z_start,0)).tolist()
r_stop = np.maximum(r_start, (r_stop - np.maximum(r_stop - zs,0))).tolist()
z_stop = (np.minimum(z_stop, zs)).tolist()

a = [slice(start,stop) for start,stop in zip(r_start, r_stop)]
b = [slice(start,stop) for start,stop in zip(z_start, z_stop)]
r[a] = z[b]
print(z)
print(r)

[[9 2 4 6 8 1 7 0 6 5]
 [7 9 3 8 2 7 4 4 1 5]
 [7 9 9 0 8 2 9 9 2 6]
 [4 7 0 4 6 7 0 5 1 1]
 [7 7 8 0 2 9 5 5 1 4]
 [1 0 8 3 6 1 4 2 7 5]
 [3 9 1 8 8 2 0 4 5 6]
 [2 7 0 5 1 3 0 1 1 4]
 [1 2 3 5 1 7 1 8 6 6]
 [8 7 2 3 5 0 6 6 1 7]]
[[0 0 0 0 0]
 [0 9 2 4 6]
 [0 7 9 3 8]
 [0 7 9 9 0]
 [0 4 7 0 4]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [77]:
z = np.arange(1, 15, dtype=np.uint32)
r = stride_tricks.as_strided(z, (11, 4), (4, 4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [78]:
z = np.random.uniform(0, 1, (10, 10))
u, s, v = np.linalg.svd(z)
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [79]:
z = np.random.randint(0, 10, 50)
print(np.bincount(z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [80]:
z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (z.shape[0] - 3)
j = 1 + (z.shape[1] - 3)
c = stride_tricks.as_strided(z, shape=(i, j, n, n), strides=z.strides + z.strides)
print(c)

[[[[2 1 1]
   [1 4 1]
   [3 1 1]]

  [[1 1 2]
   [4 1 4]
   [1 1 2]]

  [[1 2 1]
   [1 4 3]
   [1 2 2]]

  [[2 1 1]
   [4 3 1]
   [2 2 1]]

  [[1 1 0]
   [3 1 2]
   [2 1 2]]

  [[1 0 0]
   [1 2 2]
   [1 2 3]]

  [[0 0 4]
   [2 2 0]
   [2 3 3]]

  [[0 4 1]
   [2 0 1]
   [3 3 3]]]


 [[[1 4 1]
   [3 1 1]
   [2 0 1]]

  [[4 1 4]
   [1 1 2]
   [0 1 0]]

  [[1 4 3]
   [1 2 2]
   [1 0 4]]

  [[4 3 1]
   [2 2 1]
   [0 4 3]]

  [[3 1 2]
   [2 1 2]
   [4 3 3]]

  [[1 2 2]
   [1 2 3]
   [3 3 0]]

  [[2 2 0]
   [2 3 3]
   [3 0 2]]

  [[2 0 1]
   [3 3 3]
   [0 2 0]]]


 [[[3 1 1]
   [2 0 1]
   [0 3 0]]

  [[1 1 2]
   [0 1 0]
   [3 0 2]]

  [[1 2 2]
   [1 0 4]
   [0 2 1]]

  [[2 2 1]
   [0 4 3]
   [2 1 4]]

  [[2 1 2]
   [4 3 3]
   [1 4 0]]

  [[1 2 3]
   [3 3 0]
   [4 0 4]]

  [[2 3 3]
   [3 0 2]
   [0 4 2]]

  [[3 3 3]
   [0 2 0]
   [4 2 2]]]


 [[[2 0 1]
   [0 3 0]
   [0 0 0]]

  [[0 1 0]
   [3 0 2]
   [0 0 4]]

  [[1 0 4]
   [0 2 1]
   [0 4 4]]

  [[0 4 3]
   [2 1 4]
   [4 4 2]]

  [[4 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [81]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(z):
    return np.asarray(z + z.T - np.diag(z.diagonal())).view(Symetric)

s = symetric(np.random.randint(0, 10, (5, 5)))
s[2,3] = 42
print(s)

[[ 3  7  7 11  7]
 [ 7  6  2 12 14]
 [ 7  2  0 42 13]
 [11 12 42  5 13]
 [ 7 14 13 13  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [82]:
p, n = 10, 20
m = np.ones((p, n, n))
v = np.ones((p, n, 1))
s = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(s)

[[ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [83]:
z = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0),
                                       np.arange(0, z.shape[1], k), axis=1)
print(s)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [84]:
def iterate(z):
    n = (z[0:-2,0:-2] + z[0:-2,1:-1] + z[0:-2,2:] +
         z[1:-1,0:-2]                + z[1:-1,2:] +
         z[2:  ,0:-2] + z[2:  ,1:-1] + z[2:  ,2:])
    birth = (n == 3) & (z[1:-1,1:-1]==0)
    survive = ((n == 2) | (n == 3)) & (z[1:-1,1:-1]==1)
    z[...] = 0
    z[1:-1,1:-1][birth | survive] = 1
    return z

z = np.random.randint(0, 2, (50, 50))
for i in range(100): z = iterate(z)
print(z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0
  1 1 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
  0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [85]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print (z[np.argsort(z)[-n:]])
print (z[np.argpartition(-z, n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9996 9999 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [87]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [89]:
z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(r)

[(b'Hello',  2.5, 3) (b'World',  3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [91]:
x = np.random.rand(5e7)
%timeit np.power(x, 3)
%timeit x * x * x
%timeit np.einsum('i, i, i -> i', x, x, x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [92]:
a = np.random.randint(0, 5, (8, 3))
b = np.random.randint(0, 5, (2, 2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3, 1)).all(1))[0]
print(rows)

[0 1 2 3 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [93]:
z = np.random.randint(0, 5, (10, 3))
print(z)
e = np.all(z[:,1:] == z[:,:-1], axis=1)
u = z[~e]
print(u)
u = z[z.max(axis=1) != z.min(axis=1),:]
print(u)

[[4 3 0]
 [0 3 2]
 [3 3 0]
 [2 4 4]
 [4 1 2]
 [2 1 1]
 [1 1 3]
 [1 2 1]
 [3 0 2]
 [4 2 4]]
[[4 3 0]
 [0 3 2]
 [3 3 0]
 [2 4 4]
 [4 1 2]
 [2 1 1]
 [1 1 3]
 [1 2 1]
 [3 0 2]
 [4 2 4]]
[[4 3 0]
 [0 3 2]
 [3 3 0]
 [2 4 4]
 [4 1 2]
 [2 1 1]
 [1 1 3]
 [1 2 1]
 [3 0 2]
 [4 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [94]:
i = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
b = ((i.reshape(-1,1) & (2 ** np.arange(8))) != 0).astype(int)
print(b[:,::-1])
i = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(i[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [95]:
z = np.random.randint(0, 2, (6, 3))
t = np.ascontiguousarray(z).view(np.dtype((np.void, z.dtype.itemsize * z.shape[1])))
_, idx = np.unique(t, return_index=True)
uz = z[idx]
print(uz)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [96]:
a = np.random.uniform(0, 1, 10)
b = np.random.uniform(0, 1, 10)
np.einsum('i->', a)
np.einsum('i,i->i', a, b)
np.einsum('i,i', a, b)
np.einsum('i,j->ij', a, b)

array([[ 0.02982496,  0.01318979,  0.04321408,  0.01466157,  0.04045937,
         0.04815806,  0.02558693,  0.01549914,  0.01143581,  0.03506264],
       [ 0.09045712,  0.04000375,  0.13106542,  0.04446756,  0.12271057,
         0.14606017,  0.07760345,  0.04700785,  0.03468406,  0.10634264],
       [ 0.5631156 ,  0.24903219,  0.81591129,  0.27682038,  0.76390044,
         0.90925693,  0.48309865,  0.29263425,  0.21591594,  0.66200645],
       [ 0.5395161 ,  0.23859555,  0.78171742,  0.26521916,  0.73188628,
         0.87115105,  0.46285256,  0.28037029,  0.20686716,  0.63426255],
       [ 0.27602632,  0.12206985,  0.39994096,  0.13569098,  0.37444643,
         0.44569684,  0.23680385,  0.14344258,  0.10583703,  0.32450034],
       [ 0.4952591 ,  0.21902334,  0.71759243,  0.243463  ,  0.67184899,
         0.79968974,  0.42488434,  0.25737127,  0.18989766,  0.58223342],
       [ 0.15101552,  0.06678509,  0.2188099 ,  0.07423729,  0.20486171,
         0.2438432 ,  0.12955669,  0.07847823

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [98]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)
dr = (np.diff(x) ** 2 + np.diff(y) ** 2) ** .5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
print(r_int, x_int, y_int)

[   0.            2.48788858    4.97577716    7.46366574    9.95155432
   12.43944289   14.92733147   17.41522005   19.90310863   22.39099721
   24.87888579   27.36677437   29.85466295   32.34255152   34.8304401
   37.31832868   39.80621726   42.29410584   44.78199442   47.269883
   49.75777158   52.24566016   54.73354873   57.22143731   59.70932589
   62.19721447   64.68510305   67.17299163   69.66088021   72.14876879
   74.63665736   77.12454594   79.61243452   82.1003231    84.58821168
   87.07610026   89.56398884   92.05187742   94.539766     97.02765457
   99.51554315  102.00343173  104.49132031  106.97920889  109.46709747
  111.95498605  114.44287463  116.9307632   119.41865178  121.90654036
  124.39442894  126.88231752  129.3702061   131.85809468  134.34598326
  136.83387184  139.32176041  141.80964899  144.29753757  146.78542615
  149.27331473  151.76120331  154.24909189  156.73698047  159.22486904
  161.71275762  164.2006462   166.68853478  169.17642336  171.66431194
  174.152

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [99]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
m = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
m &= (x.sum(axis=-1) == n)
print(x[m])

[[ 2.  0.  1.  1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [100]:
x = np.random.randn(100)
n = 1000
idx = np.random.randint(0, x.size, (n, x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1706901   0.17269279]
